// react-client/src/pages/Friends.tsx
// src/pages/Friends.tsx
import React, { useState, useEffect } from 'react';
import { useAuth } from '../hooks/useAuth';
import Header from '../components/Header';
import { User, Friendship } from '../types';
import { del, get, post, put } from '../api/client'; // Import basic API functions

const Friends: React.FC = () => {
  // State for users and friends
  const [users, setUsers] = useState<User[]>([]);
  const [friends, setFriends] = useState<Friendship[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  
  useEffect(() => {
    fetchFriendsData();
  }, []);
  
  const fetchFriendsData = async () => {
    try {
      setIsLoading(true);
      setError(null);
      
      // Use the client directly since we haven't created the friendsApi yet
      const response = await get<{users: User[], friends: Friendship[]}>('/users/overview');
      setUsers(response.users);
      setFriends(response.friends);
    } catch (error) {
      console.error('Error fetching friends data:', error);
      setError('Failed to load friends data');
    } finally {
      setIsLoading(false);
    }
  };
  
  // Function to handle friend request, accepting or removing friendship
  const handleFriendAction = async (user: User, action: 'request' | 'accept' | 'remove') => {
    try {
      if (action === 'request') {
        // Send friend request
        const response = await post<Friendship>('/friendships', {
          addressee_id: user.id
        });
        
        // Update user in the list
        setUsers(users.map(u => 
          u.id === user.id ? { 
            ...u, 
            relationship: 'request_sent',
            friendshipId: response.id,
            liked: true 
          } : u
        ));
      } 
      else if (action === 'accept' && user.friendshipId) {
        // Accept friend request
        const response = await put<Friendship>(`/friendships/${user.friendshipId}`, {
          status: 'accepted'
        });
        
        // Remove from users list and add to friends list
        setUsers(users.filter(u => u.id !== user.id));
        setFriends([...friends, {
          id: response.id,
          status: 'accepted',
          created_at: response.created_at,
          updated_at: response.updated_at,
          friend: user
        }]);
      }
      else if (action === 'remove' && user.friendshipId) {
        // Remove friendship
        await del(`/friendships/${user.friendshipId}`);
        
        if (user.relationship === 'friends') {
          // Remove from friends list
          setFriends(friends.filter(f => f.id !== user.friendshipId));
          // Add back to users with 'none' relationship
          setUsers([...users, { 
            ...user, // Fix: use 'user' instead of 'u'
            relationship: 'none', 
            friendshipId: null,
            liked: false 
          }]);
        } else {
          // Just update the user in the list
          setUsers(users.map(u => 
            u.id === user.id ? { 
              ...u, 
              relationship: 'none', 
              friendshipId: null,
              liked: false 
            } : u
          ));
        }
      }
    } catch (error) {
      console.error('Error handling friend action:', error);
      setError('An error occurred. Please try again.');
    }
  };
  
  // Helper function to determine button text based on relationship
  const getButtonText = (user: User) => {
    switch (user.relationship) {
      case 'none': 
        return 'Like';
      case 'request_sent': 
        return 'Mog ni mehr';
      case 'request_received': 
        return 'Like back';
      case 'friends': 
        return 'Mog ni mehr';
      default: 
        return 'Add Friend';
    }
  };
  
  // Helper function to determine action based on relationship
  const getAction = (user: User): 'request' | 'accept' | 'remove' => {
    switch (user.relationship) {
      case 'none': 
        return 'request';
      case 'request_sent': 
        return 'remove';
      case 'request_received': 
        return 'accept';
      case 'friends': 
        return 'remove';
      default: 
        return 'request';
    }
  };

  return (
    <div className="font-mono max-w-4xl mx-auto p-4">
      <Header />
      
      <h1 className="text-2xl font-bold mb-6">Friends</h1>
      
      {error && (
        <div className="border border-red-500 p-2 mb-4 text-red-700 bg-red-100">
          {error}
        </div>
      )}
      
      {isLoading ? (
        <div className="p-4 text-center">Loading...</div>
      ) : (
        <>
          {/* People to Friend Section */}
          <section className="mb-8">
            <h2 className="text-xl font-bold mb-4 border-b border-gray-300 pb-2">People to Friend</h2>
            
            {users.length > 0 ? (
              <ul className="space-y-4">
                {users.map(user => (
                  <li key={user.id} className="border border-gray-300 p-4 flex justify-between items-center">
                    <div>
                      <p className="font-bold">{user.username}</p>
                      {user.relationship === 'request_received' && (
                        <p className="text-sm text-green-700">Sent you a friend request!</p>
                      )}
                    </div>
                    
                    <button 
                      className="border border-gray-500 px-4 py-1 hover:bg-gray-300"
                      onClick={() => handleFriendAction(user, getAction(user))}
                    >
                      {getButtonText(user)}
                    </button>
                  </li>
                ))}
              </ul>
            ) : (
              <p className="text-gray-600">No users found.</p>
            )}
          </section>
          
          {/* My Friends Section */}
          <section>
            <h2 className="text-xl font-bold mb-4 border-b border-gray-300 pb-2">My Friends</h2>
            
            {friends.length > 0 ? (
              <ul className="space-y-4">
                {friends.map(friendship => (
                  <li key={friendship.id} className="border border-gray-300 p-4 flex justify-between items-center">
                    <div>
                      <p className="font-bold">{friendship.friend.username}</p>
                    </div>
                    <button 
                      className="border border-gray-500 bg-red-100 text-red-700 px-4 py-1 hover:bg-red-200"
                      onClick={() => handleFriendAction(
                        { 
                          ...friendship.friend, 
                          relationship: 'friends', 
                          friendshipId: friendship.id 
                        },
                        'remove'
                      )}
                    >
                      Remove
                    </button>
                  </li>
                ))}
              </ul>
            ) : (
              <p className="text-gray-600">You don't have any friends yet.</p>
            )}
          </section>
        </>
      )}
    </div>
  );
};

export default Friends;

// CLIENT/src/routes/friends/+page.svelte
<script lang="ts">
    import { onMount } from 'svelte';
    import { goto } from '$app/navigation';
    
    // Define user type with the new relationship field
    interface User {
        id: number;
        username: string;
        email: string; // Added email property
        relationship: string; // "none", "friends", "request_sent", "request_received"
        friendshipId: number | null;
        liked: boolean;
        hasLikedCurrentUser: boolean;
    }
    
    interface Friend {
        id: number;
        friend: {
            id: number;
            username: string;
            email: string;
        };
        status: string;
    }
    
    // State variables
    let users = $state<User[]>([]);
    let friends = $state<Friend[]>([]);
    let isLoading = $state(true);
    let errorMessage = $state('');

    onMount(async () => {
        const token = localStorage.getItem('authToken');
        if (!token) {
            goto('/');
            return;
        }
        
        try {
            const response = await fetch('/api/friends', {
                headers: {
                    'Authorization': `Bearer ${token}`
                }
            });
            
            if (response.ok) {
                const data = await response.json();
                users = data.users;
                friends = data.friends;
            } else {
                errorMessage = 'Failed to load users';
            }
        } catch (error) {
            console.error('Error loading friends data:', error);
            errorMessage = 'An error occurred. Please try again.';
        } finally {
            isLoading = false;
        }
    });

    // Toggle function now handles both sending and retracting friend requests
    async function toggleFriendship(user: User) {
    const token = localStorage.getItem('authToken');
    if (!token) return;
    
    // If the user has sent a request that we need to accept
    if (user.relationship === 'request_received' && user.friendshipId) {
        try {
            // Use PUT to update the existing friendship
            const response = await fetch(`/api/friends/${user.friendshipId}`, {
                method: 'PUT',
                headers: {
                    'Content-Type': 'application/json',
                    'Authorization': `Bearer ${token}`
                },
                body: JSON.stringify({ status: 'accepted' })
            });
            
            if (response.ok) {
                // Move this user to the friends list
                const updatedFriendship = await response.json();
                
                // Update the users list to remove this user
                users = users.filter(u => u.id !== user.id);
                
                // Add to friends list with the proper structure
                friends = [...friends, {
                    id: updatedFriendship.id,
                    friend: {
                        id: user.id,
                        username: user.username,
                        email: user.email // Ensure email is included
                    },
                    status: 'accepted'
                }];
            } else {
                const errorData = await response.json();
                errorMessage = errorData.detail || 'Failed to accept friend request';
            }
        } catch (error) {
            console.error('Error accepting friend request:', error);
            errorMessage = 'An error occurred. Please try again.';
        }
    }
    // If there's already a friendship (sent request), retract it
    else if (user.relationship === 'request_sent' && user.friendshipId) {
        try {
            const response = await fetch(`/api/friends/${user.friendshipId}`, {
                method: 'DELETE',
                headers: {
                    'Authorization': `Bearer ${token}`
                }
            });
            
            if (response.ok) {
                // Update the user's relationship status
                users = users.map(u => 
                    u.id === user.id ? { 
                        ...u, 
                        relationship: 'none', 
                        liked: false, 
                        friendshipId: null 
                    } : u
                );
            } else {
                const errorData = await response.json();
                errorMessage = errorData.detail || 'Failed to retract friend request';
            }
        } catch (error) {
            console.error('Error retracting friend request:', error);
            errorMessage = 'An error occurred. Please try again.';
        }
    } 
    // If no friendship, send a new request
    else if (user.relationship === 'none') {
        try {
            const response = await fetch('/api/friends', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'Authorization': `Bearer ${token}`
                },
                body: JSON.stringify({ addressee_id: user.id })
            });
            
            if (response.ok) {
                const data = await response.json();
                // Update the user's relationship status
                users = users.map(u => 
                    u.id === user.id ? { 
                        ...u, 
                        relationship: 'request_sent', 
                        liked: true, 
                        friendshipId: data.id 
                    } : u
                );
            } else {
                const errorData = await response.json();
                errorMessage = errorData.detail || 'Failed to send friend request';
            }
        } catch (error) {
            console.error('Error sending friend request:', error);
            errorMessage = 'An error occurred. Please try again.';
        }
    }
    // If they're already friends, remove the friendship
    else if (user.relationship === 'friends' && user.friendshipId) {
        try {
            const response = await fetch(`/api/friends/${user.friendshipId}`, {
                method: 'DELETE',
                headers: {
                    'Authorization': `Bearer ${token}`
                }
            });
            
            if (response.ok) {
                // Update the user's relationship status and remove from friends list
                users = users.map(u => 
                    u.id === user.id ? { 
                        ...u, 
                        relationship: 'none', 
                        liked: false, 
                        friendshipId: null 
                    } : u
                );
                friends = friends.filter(f => f.id !== user.friendshipId);
            } else {
                const errorData = await response.json();
                errorMessage = errorData.detail || 'Failed to remove friendship';
            }
        } catch (error) {
            console.error('Error removing friendship:', error);
            errorMessage = 'An error occurred. Please try again.';
        }
    }
}
    
    // Function to remove a friendship
    async function removeFriendship(friendshipId: number) {
        const token = localStorage.getItem('authToken');
        if (!token) return;

        try {
            const response = await fetch(`/api/friends/${friendshipId}`, {
                method: 'DELETE',
                headers: {
                    'Authorization': `Bearer ${token}`
                }
            });
            
            if (response.ok) {
                // Find the friend to update in the users list too
                const removedFriend = friends.find(f => f.id === friendshipId);
                if (removedFriend) {
                    users = users.map(u => 
                        u.id === removedFriend.friend.id ? {
                            ...u,
                            relationship: 'none',
                            liked: false,
                            friendshipId: null
                        } : u
                    );
                }
                // Remove from friends list
                friends = friends.filter(f => f.id !== friendshipId);
            } else {
                const errorData = await response.json();
                errorMessage = errorData.detail || 'Failed to remove friendship';
            }
        } catch (error) {
            console.error('Error removing friendship:', error);
            errorMessage = 'An error occurred. Please try again.';
        }
    }
    
    // Helper function to determine button text based on relationship
    function getButtonText(user: User) {
        switch (user.relationship) {
            case 'none': 
                return 'Like';
            case 'request_sent': 
                return 'Mog ni mehr';
            case 'request_received': 
                return 'Accept';
            case 'friends': 
                return 'Remove';
            default: 
                return 'Like';
        }
    }
</script>

<svelte:head>
    <title>Friends | Bone Social Web Project</title>
</svelte:head>

<main>
    {#if errorMessage}
        <div class="border border-red-500 p-2 mb-4 text-red-700 bg-red-100">
            {errorMessage}
        </div>
    {/if}
    
    {#if isLoading}
        <p>Loading...</p>
    {:else}
        <!-- Users section -->
        <section class="mb-8">
            <h2 class="text-xl font-bold mb-4 border-b border-gray-300 pb-2">People to friend</h2>
            
            {#if users.length > 0}
                <ul class="space-y-4">
                    {#each users as user}
                        <li class="border border-gray-300 p-4 flex justify-between items-center">
                            <div>
                                <p class="font-bold">{user.username}</p>
                                <!-- Show a special message for users who have sent a request -->
                                {#if user.relationship === 'request_received'}
                                    <p class="text-sm text-green-700">Sent you a friend request!</p>
                                {/if}
                            </div>
                            
                            <!-- Only show button for non-friends -->
                            {#if user.relationship !== 'friends'}
                                <button 
                                    class="border border-gray-500 px-4 py-1 hover:bg-gray-300"
                                    on:click={() => toggleFriendship(user)}
                                >
                                    {getButtonText(user)}
                                </button>
                            {/if}
                        </li>
                    {/each}
                </ul>
            {:else}
                <p class="text-gray-600">No users found.</p>
            {/if}
        </section>
        
        <!-- Friends section -->
        <section>
            <h2 class="text-xl font-bold mb-4 border-b border-gray-300 pb-2">My Friends</h2>
            
            {#if friends.length > 0}
                <ul class="space-y-4">
                    {#each friends as friendship}
                        <li class="border border-gray-300 p-4 flex justify-between items-center">
                            <div>
                                <p class="font-bold">{friendship.friend.username}</p>
                            </div>
                            <button 
                                class="border border-gray-500 bg-red-100 text-red-700 px-4 py-1 hover:bg-red-200"
                                on:click={() => removeFriendship(friendship.id)}
                            >
                                Remove
                            </button>
                        </li>
                    {/each}
                </ul>
            {:else}
                <p class="text-gray-600">You don't have any friends yet.</p>
            {/if}
        </section>
    {/if}
</main>
