// react-client/src/components/Header.tsx
import React from 'react';
import { Link } from 'react-router-dom';
import { useAuth } from '../hooks/useAuth';
import NotificationBell from './NotificationBell';

const Header: React.FC = () => {
  const { username } = useAuth();

  return (
    <header className="mb-8 border-b border-gray-400 pb-4">
      <div className="flex justify-between items-center">
        <h1 className="text-2xl font-bold">The Bone Social Web Project</h1>
        <div className="flex items-center space-x-4">
          <Link to="/dashboard" className="text-blue-700 underline hover:text-blue-900">
            Home
          </Link>
          <Link to="/friends" className="text-blue-700 underline hover:text-blue-900">
            Friends
          </Link>
          <Link to="/profile" className="text-blue-700 underline hover:text-blue-900">
            {username}
          </Link>
          <div className="mx-2">
            <NotificationBell />
          </div>
        </div>
      </div>
    </header>
  );
};

export default Header;

// CLIENT/src/lib/components/Header.svelte
<script lang="ts">
    // This component will only rerender if these props change
    export let username: string;
</script>

<header class="mb-8 border-b border-gray-400 pb-4">
    <div class="flex justify-between items-center">
        <h1 class="text-2xl font-bold">The Bone Social Web Project</h1>
        <a 
            href="/profile"
            class="border border-gray-500 bg-gray-200 px-4 py-1 hover:bg-gray-300"
        >
            Profile
        </a>
    </div>
    <p class="text-gray-700 mt-2">Welcome, {username}.</p>
</header>
